---
- name: install demo 
  hosts: test_servers
  sudo: yes
  tasks:
    - name: Install list of packages
      action: apt pkg={{item}} state=present
      with_items:
        - mc
        - mtr
        - screen
